Runbook page
seecloud/fuel-devops-portal pull request #68
Opened 2016-12-27 13:53 UTC by Cesarsar

2016-12-28 13:46 UTC, vkramskikh requested changes

2016-12-28 13:46 UTC, vkramskikh commented on src/components/DownloadFileButton.js
> +export default class DownloadFileButton extends Component {
I don't think this controls is needed at all - there is not so much logic. Actually it's just saveFile method which can be passed as onClick

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookForm.js
> +  @observable key = Date.now()
I'd name it somehow more meaningful and create a separate action with meaningful name to update it. It took me about a minute to recall what this hack is for :)

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookForm.js
> +    let parameters = clone(this.props.data.parameters.slice());
Why do we need both clone and slice here?

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookForm.js
> +              <div className='row' key={index}>
Can we use tag itself here? Using index for key is last resort option and here there are better options

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookPage.js
> +  @action
o_O

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookPage.js
> +  componentWillMount() {
Please use constructor()

2016-12-28 13:46 UTC, vkramskikh commented on src/components/runbooks/RunbookPage.js
> +    transaction(() => {
It's not necessary to use transaction withing action - all actions are transactions

2016-12-28 14:53 UTC, Cesarsar commented on src/components/runbooks/RunbookForm.js
> +              <div className='row' key={index}>
Nope as we edit tag string here and key prop will change for the row on each user input.
Changed to 'tag'+index

2016-12-29 11:09 UTC, vkramskikh commented on src/components/runbooks/RunbookRunsPage.js
> +                            '/region/' + runbookRun.runbook.regionId +
Please use encodeURIComponent as we do everywhere else

2016-12-29 11:09 UTC, vkramskikh commented on src/components/runbooks/RunbookForm.js
> +    parameters[index][attr] = value;
Why do you clone parameters at all, if you're mutating the value directly anyway and it is mutated in the old array also?

2016-12-29 13:42 UTC, vkramskikh approved these changes

2016-12-29 13:42 UTC, merged